/*
 * Copyright 2010-2020 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.decompiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("libraries/tools/kotlin-decompiler/testData/.")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class IrDecompilerTextTestCaseGenerated extends AbstractIrDecompilerTextTestCase {
    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
    }

    public void testAllFilesPresentIn_() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("libraries/tools/kotlin-decompiler/testData/."), Pattern.compile("^(.+)\\.kt$"), null, true, "box");
    }

    @TestMetadata("simpleOperators.kt")
    public void testSimpleOperators() throws Exception {
        runTest("libraries/tools/kotlin-decompiler/testData/./simpleOperators.kt");
    }

    @TestMetadata("libraries/tools/kotlin-decompiler/testData/./classes")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Classes extends AbstractIrDecompilerTextTestCase {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
        }

        public void testAllFilesPresentInClasses() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("libraries/tools/kotlin-decompiler/testData/./classes"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @TestMetadata("classes.kt")
        public void testClasses() throws Exception {
            runTest("libraries/tools/kotlin-decompiler/testData/./classes/classes.kt");
        }

        @TestMetadata("primaryConstructor.kt")
        public void testPrimaryConstructor() throws Exception {
            runTest("libraries/tools/kotlin-decompiler/testData/./classes/primaryConstructor.kt");
        }

        @TestMetadata("secondaryConstructorWithInitializersFromClassBody.kt")
        public void testSecondaryConstructorWithInitializersFromClassBody() throws Exception {
            runTest("libraries/tools/kotlin-decompiler/testData/./classes/secondaryConstructorWithInitializersFromClassBody.kt");
        }

        @TestMetadata("secondaryConstructors.kt")
        public void testSecondaryConstructors() throws Exception {
            runTest("libraries/tools/kotlin-decompiler/testData/./classes/secondaryConstructors.kt");
        }
    }
}
