/*
 * Copyright 2010-2019 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.highlighter;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("idea/testData/highlighter/typing")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class HighlightAndTypingTestGenerated extends AbstractHighlightAndTypingTest {
    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
    }

    public void testAllFilesPresentInTyping() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/highlighter/typing"), Pattern.compile("^([\\w\\-_]+)\\.kt$"), TargetBackend.ANY, true);
    }

    @TestMetadata("PartialAnalysis1.kt")
    public void testPartialAnalysis1() throws Exception {
        runTest("idea/testData/highlighter/typing/PartialAnalysis1.kt");
    }

    @TestMetadata("PartialAnalysis1Comment.kt")
    public void testPartialAnalysis1Comment() throws Exception {
        runTest("idea/testData/highlighter/typing/PartialAnalysis1Comment.kt");
    }

    @TestMetadata("PartialAnalysis1Error.kt")
    public void testPartialAnalysis1Error() throws Exception {
        runTest("idea/testData/highlighter/typing/PartialAnalysis1Error.kt");
    }

    @TestMetadata("PartialAnalysis1SwapLines.kt")
    public void testPartialAnalysis1SwapLines() throws Exception {
        runTest("idea/testData/highlighter/typing/PartialAnalysis1SwapLines.kt");
    }

    @TestMetadata("PartialAnalysis1Unused.kt")
    public void testPartialAnalysis1Unused() throws Exception {
        runTest("idea/testData/highlighter/typing/PartialAnalysis1Unused.kt");
    }
}
